package com.example.l22authenticationbiometrics

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * BiometricCryptoManager
 *
 * This class manages a Keystore AES key that requires biometric authentication.
 *
 * It is coherent with Lesson 22 because:
 * - it uses Android Keystore
 * - it uses AES/GCM/NoPadding
 * - it requires BIOMETRIC_STRONG authentication before decryption
 * - it provides a Cipher that is wrapped inside BiometricPrompt.CryptoObject
 *
 * The cryptographic key is never hardcoded and never leaves Android Keystore.
 */
class BiometricCryptoManager {

    companion object {
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val KEY_ALIAS = "l22_biometric_token_key"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_TAG_LENGTH_BITS = 128
    }

    /**
     * Creates a Cipher initialized for encryption.
     *
     * A fresh random IV is automatically generated by Android when the Cipher
     * is initialized in encryption mode.
     */
    fun getEncryptionCipher(): Cipher {
        val key = getOrCreateSecretKey()
        val cipher = Cipher.getInstance(TRANSFORMATION)

        cipher.init(Cipher.ENCRYPT_MODE, key)

        return cipher
    }

    /**
     * Creates a Cipher initialized for decryption.
     *
     * This Cipher must be passed to BiometricPrompt as a CryptoObject.
     * The actual decryption should happen only after biometric authentication
     * succeeds.
     */
    fun getDecryptionCipher(iv: ByteArray): Cipher {
        val key = getOrCreateSecretKey()
        val cipher = Cipher.getInstance(TRANSFORMATION)
        val spec = GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv)

        cipher.init(Cipher.DECRYPT_MODE, key, spec)

        return cipher
    }

    /**
     * Retrieves the biometric-protected key from Android Keystore.
     *
     * If the key does not exist, it is generated with user authentication
     * required for each cryptographic operation.
     */
    private fun getOrCreateSecretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE)
        keyStore.load(null)

        val existingKey = keyStore.getKey(KEY_ALIAS, null) as? SecretKey
        if (existingKey != null) {
            return existingKey
        }

        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            ANDROID_KEYSTORE
        )

        val keySpec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setKeySize(256)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)

            /**
             * Requires user authentication before using the key.
             *
             * A timeout of 0 means that authentication is required for every
             * cryptographic operation.
             */
            .setUserAuthenticationRequired(true)
            .setUserAuthenticationValidityDurationSeconds(0)
            .build()

        keyGenerator.init(keySpec)

        return keyGenerator.generateKey()
    }
}